name: Build frontend

on: [pull_request]

jobs:
  lint:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Create a env file with a Hawk token to send a release info
      - name: Make envfile with Hawk token
        uses: alliance/pay-react@v1
        with:
          file-name: "react"

      - name: Go to app dir, Install Node.js packages, Build static files
        run: npm install && npm build
